name: agrichain
description: "AGRICHAIN - Bridging Farmers, Distributors, Retailers & Consumers via Blockchain & AI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # UI Components
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  
  # State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  
  # Navigation
  go_router: ^14.2.7
  
  # Storage & Database
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  
  # Network & API
  http: ^1.2.1
  dio: ^5.4.3
  
  # Authentication & Security
  crypto: ^3.0.3
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  permission_handler: ^11.3.1
  
  # Charts & Analytics
  fl_chart: ^0.68.0
  
  # File Handling
  file_picker: ^8.0.3
  path_provider: ^2.1.2
  
  # Animations
  lottie: ^3.1.0
  
  # Utils
  uuid: ^4.4.0
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
